# Lab playbook - sets up the host specific shit
---
  epel_rpm: "http://download.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm"
  ol_repo_file: public-yum-ol6.repo
  repo_dir: /etc/yum.repos.d/
#  default_user: ansible
  install_os_packages: true
  configure_epel_repo: true
  configure_public_yum_repo: true
  configure_motd: true
  configure_ntp: true

  common_packages:
      - screen
      - facter
      - procps
      - module-init-tools
      - ethtool
      - bc
      - nc
      - bind-utils
      - nfs-utils
      - make
      - sysstat
      - unzip
      - openssh-clients
      - compat-libcap1
      - twm
      - collectl
      - rlwrap
      - tigervnc-server
      - ntp
      - expect
      - git
      - lvm2
      - xfsprogs
      - btrfs-progs
      - tmux
      - python-devel
      - python-pip
      - libselinux-python
